name: CI

on:
  pull_request:
  push:
  schedule:
    - cron: 0 0 * * 0

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y --no-install-recommends binfmt-support qemu-user-static
      - run: ./build.sh
      - run: ./test.sh gosu-amd64
      - run: ./test.sh gosu-i386
      - run: ./test.sh --debian gosu-amd64
      - run: ./test.sh --debian gosu-i386
      - run: docker build --pull --file hub/Dockerfile.alpine hub
      - run: docker build --pull --file hub/Dockerfile.debian hub

      - uses: actions/setup-go@v4
        with:
          go-version: 1.18
      # https://github.com/golang/vuln/commits/master
      # https://github.com/golang/vuln/releases
      # https://github.com/golang/vuln/tags
      - run: go install golang.org/x/vuln/cmd/govulncheck@v1.0.4
      # (update "go-version" above when updating this version; https://github.com/golang/vuln/blob/v1.0.1/go.mod#L3)

      - run: for gosu in gosu-*; do ./govulncheck-with-excludes.sh -mode=binary "$gosu"; done
